lunatech-labs/lunatech-lunch-planner

app/lunatech/lunchplanner/controllers/Application.scala, app/lunatech/lunchplanner/controllers/Authentication.scala, app/lunatech/lunchplanner/controllers/DishController.scala, app/lunatech/lunchplanner/services/DishService.scala, app/lunatech/lunchplanner/viewModels/DishForm.scala, app/views/admin.scala.html, build.sbt, conf/evolutions/default/7.sql, conf/evolutions/default/8.sql, conf/routes, project/plugins.sbt
Added interface to create a new dish
Added route to create a new dish
Added route to list all dishes
=> New dish creation and all dishes listing

app/lunatech/lunchplanner/controllers/Application.scala, app/lunatech/lunchplanner/controllers/Authentication.scala, app/lunatech/lunchplanner/controllers/DishController.scala, app/lunatech/lunchplanner/controllers/MenuController.scala, app/lunatech/lunchplanner/controllers/Secured.scala, app/lunatech/lunchplanner/persistence/UserTable.scala, app/lunatech/lunchplanner/services/DishService.scala, app/lunatech/lunchplanner/services/MenuDishService.scala, app/lunatech/lunchplanner/services/MenuService.scala, app/lunatech/lunchplanner/services/UserService.scala, app/lunatech/lunchplanner/viewModels/DishForm.scala, app/lunatech/lunchplanner/viewModels/MenuForm.scala, app/views/admin.scala.html, build.sbt, conf/evolutions/default/7.sql, conf/evolutions/default/8.sql, conf/routes, project/plugins.sbt
Added interface to create a new menu and add dishes to the menu
Added a list of menus after creation of menu form
Added a list of dishes after creation of dishes form
=> Added creation of menus and association of dishes to the menu

app/lunatech/lunchplanner/controllers/Application.scala, app/lunatech/lunchplanner/controllers/Authentication.scala, app/lunatech/lunchplanner/controllers/DishController.scala, app/lunatech/lunchplanner/controllers/MenuController.scala, app/lunatech/lunchplanner/controllers/MenuPerDayController.scala, app/lunatech/lunchplanner/controllers/Secured.scala, app/lunatech/lunchplanner/models/MenuPerDay.scala, app/lunatech/lunchplanner/persistence/UserTable.scala, app/lunatech/lunchplanner/services/DishService.scala, app/lunatech/lunchplanner/services/MenuDishService.scala, app/lunatech/lunchplanner/services/MenuPerDayService.scala, app/lunatech/lunchplanner/services/MenuService.scala, app/lunatech/lunchplanner/services/UserService.scala, app/lunatech/lunchplanner/viewModels/DishForm.scala, app/lunatech/lunchplanner/viewModels/MenuForm.scala, app/lunatech/lunchplanner/viewModels/MenuPerDayForm.scala, app/views/admin.scala.html, app/views/datepicker.scala.html, build.sbt, conf/evolutions/default/7.sql, conf/evolutions/default/8.sql, conf/routes, project/plugins.sbt
Added new tab on admin called "scheduling of menus" that allow to do the association of menus with dates (MenuPerDay)
Added list of menus per day scheduled as well
=> Added scheduling of menus in admin (MenuPerDay)

clevercloud/sbt.json
Add clever cloud config folder and file
=> Add clever cloud config folder and file

conf/application.conf
Modified the DB URL to POSTGRESQL_ADDON_URI
=> Modified the DB URL to POSTGRESQL_ADDON_URI

conf/application.conf
Fix connection for clever cloud DB
=> Fix connection for clever cloud DB

conf/application.conf
=> Added play secret

app/lunatech/lunchplanner/services/UserService.scala
The additions of new user should only return after adding the user is completed.
=> Fix adding new users.

app/lunatech/lunchplanner/controllers/MenuPerDayPerPersonController.scala, app/lunatech/lunchplanner/services/MenuPerDayPerPersonService.scala
Fix refresh of the planned meals separator
=> Fix refresh planned meals

app/views/menuPerDayPerPerson.scala.html
Added the details of the dishes in the planned meals separator
=> Added the details of the dishes in the planned meals separator

conf/application.conf
=> Added Vijay as admin

conf/application.conf
Added max and min number of connections to the DB
=> Added max and min number of connections to the DB

app/lunatech/lunchplanner/persistence/MenuPerDayTable.scala, app/lunatech/lunchplanner/services/MenuPerDayService.scala, test/lunatech/lunchplanner/persistence/MenuPerDayTableSpec.scala
Modified the list of planned meals to show only future meals
=> Modified the list of planned meals to show only future meals

conf/application.conf
Modified connection pool library to attempt to setup max DB connections
=> Modified connection pool library to attempt to setup max DB connections

app/lunatech/lunchplanner/controllers/Application.scala, app/lunatech/lunchplanner/controllers/DishController.scala, app/lunatech/lunchplanner/controllers/MenuController.scala, app/lunatech/lunchplanner/controllers/MenuPerDayController.scala, app/lunatech/lunchplanner/controllers/MenuPerDayPerPersonController.scala, app/lunatech/lunchplanner/controllers/Secured.scala, app/lunatech/lunchplanner/models/User.scala, app/lunatech/lunchplanner/persistence/MenuPerDayTable.scala, app/lunatech/lunchplanner/persistence/UserTable.scala, app/lunatech/lunchplanner/services/DishService.scala, app/lunatech/lunchplanner/services/MenuDishService.scala, app/lunatech/lunchplanner/services/MenuPerDayPerPersonService.scala, app/lunatech/lunchplanner/services/MenuPerDayService.scala, app/lunatech/lunchplanner/services/MenuService.scala, app/lunatech/lunchplanner/viewModels/MenuPerDayForm.scala, app/views/admin/dish/dishDetails.scala.html, app/views/admin/dish/dishes.scala.html, app/views/admin/dish/newDish.scala.html, app/views/admin/menu/menuDetails.scala.html, app/views/admin/menu/menus.scala.html, app/views/admin/menu/newMenu.scala.html, app/views/admin/menuPerDay/menuPerDayDetails.scala.html, app/views/admin/menuPerDay/menusPerDay.scala.html, app/views/admin/menuPerDay/newMenuPerDay.scala.html, app/views/datepickerrange.scala.html, app/views/main.scala.html, app/views/menuPerDayPerPerson.scala.html, conf/routes, public/javascripts/main.js
By default, only future meals in the "schedules" separator are shown
Added a date range filter that allows filtering a custom time frame.
Some refactoring done
=> Add date filter list schedules

conf/application.conf
Reverted the max connections restriction because it was causing errors.
More connections are necessary
=> Reverted the max connections restriction

app/lunatech/lunchplanner/controllers/Application.scala, app/lunatech/lunchplanner/controllers/DishController.scala, app/lunatech/lunchplanner/controllers/MenuController.scala, app/lunatech/lunchplanner/controllers/MenuPerDayController.scala, app/lunatech/lunchplanner/controllers/MenuPerDayPerPersonController.scala, app/views/admin/dish/dishes.scala.html, app/views/admin/menu/menus.scala.html, app/views/admin/menuPerDay/menusPerDay.scala.html, app/views/menuPerDayPerPerson.scala.html
Added messages send using flash scope.
The messages are shown after the user creates, updates or deletes an item and also when user update their meal attendances
=> Added feedback to user after creation / update / deletion of items

app/lunatech/lunchplanner/persistence/UserTable.scala, conf/application-test.conf, conf/evolutions/default/8.sql, test/lunatech/lunchplanner/common/TestDatabaseProvider.scala, test/lunatech/lunchplanner/controllers/MenuPerDayControllerSpec.scala, test/lunatech/lunchplanner/persistence/DishTableSpec.scala, test/lunatech/lunchplanner/persistence/MenuDishTableSpec.scala, test/lunatech/lunchplanner/persistence/MenuPerDayPerPersonSpec.scala, test/lunatech/lunchplanner/persistence/MenuPerDayTableSpec.scala, test/lunatech/lunchplanner/persistence/MenuTableSpec.scala, test/lunatech/lunchplanner/persistence/UserTableSpec.scala
Fixed unit test caused by the refactoring done to User
=> Fixed unit test caused by the refactoring done to User

app/lunatech/lunchplanner/controllers/ProfileController.scala, app/lunatech/lunchplanner/models/UserProfile.scala, app/lunatech/lunchplanner/persistence/UserProfileTable.scala, app/lunatech/lunchplanner/services/UserProfileService.scala, app/lunatech/lunchplanner/viewModels/ProfileForm.scala, app/views/admin/dish/dishes.scala.html, app/views/admin/menu/menus.scala.html, app/views/admin/menuPerDay/menusPerDay.scala.html, app/views/main.scala.html, app/views/menuPerDayPerPerson.scala.html, app/views/profile.scala.html, app/views/sideMenu.scala.html, conf/evolutions/default/9.sql, conf/routes, test/lunatech/lunchplanner/common/TestDatabaseProvider.scala, test/lunatech/lunchplanner/persistence/UserProfileTableSpec.scala
Added table UserProfile
Added separator to side menu "Profile"
In the profile user can add diet restrictions
=> Add user profile

app/lunatech/lunchplanner/controllers/MenuPerDayController.scala, app/lunatech/lunchplanner/controllers/ProfileController.scala, app/lunatech/lunchplanner/models/MenuPerDay.scala, app/lunatech/lunchplanner/models/UserProfile.scala, app/lunatech/lunchplanner/persistence/UserProfileTable.scala, app/lunatech/lunchplanner/services/UserProfileService.scala, app/lunatech/lunchplanner/viewModels/ProfileForm.scala, app/views/admin/dish/dishes.scala.html, app/views/admin/menu/menus.scala.html, app/views/admin/menuPerDay/menuPerDayDetails.scala.html, app/views/admin/menuPerDay/menusPerDay.scala.html, app/views/main.scala.html, app/views/menuPerDayPerPerson.scala.html, app/views/profile.scala.html, app/views/sideMenu.scala.html, conf/evolutions/default/9.sql, conf/routes, public/stylesheets/main.css, test/lunatech/lunchplanner/common/TestDatabaseProvider.scala, test/lunatech/lunchplanner/controllers/MenuPerDayControllerSpec.scala, test/lunatech/lunchplanner/persistence/UserProfileTableSpec.scala
Added summary of diet restriction in the details of a schedule
=> Add diet restrictions summary

app/lunatech/lunchplanner/common/DBConnection.scala, app/lunatech/lunchplanner/controllers/Application.scala, app/lunatech/lunchplanner/controllers/MenuPerDayController.scala, app/lunatech/lunchplanner/persistence/MenuPerDayPerPersonTable.scala, app/lunatech/lunchplanner/persistence/MenuPerDayTable.scala, app/lunatech/lunchplanner/services/MenuPerDayPerPersonService.scala, app/lunatech/lunchplanner/services/MenuPerDayService.scala, app/lunatech/lunchplanner/services/UserProfileService.scala, app/views/admin/menuPerDay/menuPerDayDetails.scala.html, test/lunatech/lunchplanner/persistence/MenuPerDayPerPersonSpec.scala, test/lunatech/lunchplanner/persistence/MenuPerDayTableSpec.scala
Added the list of people attending a menu per day (schedule) to the details of a menu per day (schedule)
=> Add list people attending

app/lunatech/lunchplanner/controllers/MenuPerDayPerPersonController.scala, app/lunatech/lunchplanner/viewModels/MenuPerDayPerPerson.scala, app/views/menuPerDayPerPerson.scala.html, public/javascripts/main.js
A user cannot choose more than one menu for the same day.
In case it happens an error message is displayed and the user has to save again.
=> Added validation on the selected planned meals.

app/lunatech/lunchplanner/controllers/MenuPerDayPerPersonController.scala, app/lunatech/lunchplanner/services/UserProfileService.scala
Fixed issue on schedule details when no one is attending menu.
=> Issue diet restriction summary

app/lunatech/lunchplanner/controllers/MenuPerDayController.scala, app/lunatech/lunchplanner/persistence/UserProfileTable.scala, app/lunatech/lunchplanner/services/UserService.scala, conf/evolutions/default/10.sql, test/lunatech/lunchplanner/persistence/MenuPerDayPerPersonSpec.scala
When a user was created the user profile was not. This was causing the person to not appear in the list of attendees details
=> Fix issue in the list of attendees in the details of a schedule.

project/plugins.sbt, scalastyle-config.xml
Fix issue #89 
-Add scalastyle plugin to generate style report
-Add scoverage plugin to generate test coverage
=> Code quality plugins

app/views/main.scala.html, app/views/sideMenu.scala.html, public/javascripts/side-menu.js, public/stylesheets/simple-sidebar.css
fix issue #79 
-Change colour of active sub-menu in side bar, so user can know on which menu currently they are.
=> Add tracker for active sub-menu for side menu.

app/lunatech/lunchplanner/controllers/MenuPerDayController.scala, app/lunatech/lunchplanner/data/Constants.scala, app/lunatech/lunchplanner/data/Location.scala, app/lunatech/lunchplanner/viewModels/MenuPerDayForm.scala, app/views/admin/menuPerDay/menuPerDayDetails.scala.html, app/views/admin/menuPerDay/newMenuPerDay.scala.html, public/javascripts/main.js
Code changes according to what was discussed earlier. Thanks, Sietse! :)
=> Refactored codes

app/views/admin/dish/dishDetails.scala.html, app/views/admin/dish/dishes.scala.html, app/views/admin/menu/menuDetails.scala.html, app/views/admin/menu/menus.scala.html, app/views/admin/menuPerDay/menuPerDayDetails.scala.html, app/views/admin/menuPerDay/menusPerDay.scala.html, public/javascripts/main.js
Resolves #98 
Just added a simple script for all buttons with "btn-danger" class to show confirmation dialog before submitting.
=> Confirmation dialog delete

app/lunatech/lunchplanner/controllers/ReportController.scala, app/lunatech/lunchplanner/services/ReportService.scala
Changed exporting means to stream instead of Temporary File to work in clever cloud.
=> Export report via stream

conf/application.conf
Adding my email address to the admins
=> Adding myself as an admin

app/views/admin/menu/menuDetails.scala.html
Fixed ui issue with selection checkboxes
=> 121 - checkbox issue

app/lunatech/lunchplanner/controllers/MenuPerDayPerPersonController.scala, app/lunatech/lunchplanner/controllers/SlackController.scala, app/lunatech/lunchplanner/controllers/UserController.scala, app/lunatech/lunchplanner/modules/Module.scala, app/lunatech/lunchplanner/persistence/MenuPerDayPerPersonTable.scala, app/lunatech/lunchplanner/persistence/MenuPerDayTable.scala, app/lunatech/lunchplanner/services/MenuPerDayPerPersonService.scala, app/lunatech/lunchplanner/services/MenuPerDayService.scala, app/lunatech/lunchplanner/services/SlackService.scala, app/lunatech/lunchplanner/services/UserService.scala, app/lunatech/lunchplanner/slack/LunchBotScheduler.scala, app/lunatech/lunchplanner/viewModels/SlackForm.scala, build.sbt, conf/application.conf, conf/logback.xml, conf/routes, test/lunatech/lunchplanner/services/SlackServiceSpec.scala
=> Backend implementation of Slack bot

app/views/menuPerDayPerPerson.scala.html, conf/evolutions/default/13.sql, public/javascripts/main.js
This is to prevent late entries and better tracking. Starting Thursday at 3 PM onwards 'til Friday, app won't accept anymore entries for the latest upcoming lunch schedule.
=> Added restriction for late entries and timestamps

app/lunatech/lunchplanner/controllers/ReportController.scala, app/lunatech/lunchplanner/models/Report.scala, app/lunatech/lunchplanner/persistence/MenuPerDayTable.scala, app/lunatech/lunchplanner/services/ReportService.scala, app/lunatech/lunchplanner/viewModels/ReportForm.scala, app/views/admin/report.scala.html, public/javascripts/main.js
Currently, we only get report data by month. I'm adding a year field to filter 2017, 2018 (and so on...) data.
=> Year field for Report generation

app/lunatech/lunchplanner/controllers/ReportController.scala, app/lunatech/lunchplanner/models/Report.scala, app/lunatech/lunchplanner/services/ReportService.scala
=> Added location column on reports

README.md, build.sbt, docker-compose.yml, project/plugins.sbt
Add the possibilite to spin the docker container using docker-compose
=> 140 - Add docker compose

project/build.properties, project/plugins.sbt
Upgraded sbt version to 1.1.1
Upgraded sbt-coverage to 1.5.1
Upgraded sbt-dependency-check to 1.2.3
Removed scalaStyle plugin
=> Upgraded sbt version to 1.1.1

app/lunatech/lunchplanner/services/SlackService.scala
Fix in sending broken message when there's no lunch for an upcoming Friday.
With this fix, Slack Bot will not send a message. Having Slack Bot send some other message is more a new feature for the bot, so let's do it on a different branch.
=> Slack Bot message fix

conf/application.conf
Remove DB maxConnections and minConnections constraints because it makes DB through an exception
=> Remove DB maxConnections and minConnections constraints

build.sbt, conf/application.conf
Update slick-hikaricp to version 3.2.3
Add numThreads to db configuration (together with previous max and min connections)
=> Handle DB max connections settings

conf/application.conf
Add automatic redirect to from http to https.
Removed warnings about illegal headers
=> Add automatic redirect to from http to https.

app/lunatech/lunchplanner/filters/TLSFilter.scala, conf/application.conf
Hey @wjglerum I guess this is what you meant?
=> Enable automatic https redirect

README.md, conf/application.conf
Improved configuration and setup instructions.
=> improve-first-time-setup

app/lunatech/lunchplanner/schedulers/LunchBotScheduler.scala, app/lunatech/lunchplanner/schedulers/MonthlyReportScheduler.scala, app/lunatech/lunchplanner/schedulers/actors/MonthlyReportActor.scala, app/lunatech/lunchplanner/services/EmailService.scala
=> Refactor cron jobs, improve lunch bot cron job description and add better log on EmailService

app/lunatech/lunchplanner/controllers/ReportController.scala, app/lunatech/lunchplanner/models/Report.scala, app/lunatech/lunchplanner/schedulers/actors/MonthlyReportActor.scala, app/lunatech/lunchplanner/services/MonthlyReportService.scala, app/lunatech/lunchplanner/services/ReportService.scala, app/views/admin/report.scala.html, test/lunatech/lunchplanner/services/ReportServiceSpec.scala
Modify the Monthy excel report by grouping the data by week number. 
The list of people that did not attend a schedule was removed
=> Modify the Monthy excel report by grouping the data by week number. 

.scalafmt.conf, app/lunatech/lunchplanner/controllers/RestController.scala, app/lunatech/lunchplanner/models/MenuPerDayPerPerson.scala, app/lunatech/lunchplanner/persistence/MenuPerDayPerPersonTable.scala, app/lunatech/lunchplanner/services/RestService.scala, conf/routes, test/lunatech/lunchplanner/controllers/RestControllerSpec.scala, test/lunatech/lunchplanner/data/ControllersData.scala, test/lunatech/lunchplanner/persistence/MenuPerDayPerPersonTableSpec.scala, test/lunatech/lunchplanner/services/RestServiceSpec.scala
Implement REST endpoints to attend / unattend events.
Also fix MenuPerDayPerPersonTable addOrUpdate update and add test.
=> Implement REST endpoints to attend / unattend events.
